version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=server.py
      - FLASK_RUN_HOST=0.0.0.0
    command: sh -c "flask run --host=0.0.0.0"

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
